services:
  web:
    container_name: "web"
    build:
      dockerfile: "./docker/nginx/Dockerfile"
    ports:
      - "8900:80"
    volumes:
      - "./src:/var/www/html"
  app:
    container_name: "app"
    mem_limit: 6g
    build:
      dockerfile: "./docker/php/Dockerfile"
    volumes:
      - "./src:/var/www/html"
    ports:
      - 5173:5173
