services:
  nginx:
    container_name: asset_ms_dev_nginx
    build: ./docker/nginx
    ports:
      - 8001:80
    volumes:
      - "./src:/var/www/html"
    networks:
      - asset_ms_dev_network

  app:
    container_name: asset_ms_dev_app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 5001:5001
    volumes:
      - "./src:/var/www/html"
    networks:
      - mysql_mysql_network
      - asset_ms_dev_network

networks:
  asset_ms_dev_network:
  mysql_mysql_network:
    external: true
