services:
  nginx:
    build: ./docker/nginx
    ports:
      - 8001:80
    volumes:
      - "asset_ms_dev:/var/www/html"

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 5001:5001
    volumes:
      - "asset_ms_dev:/var/www/html"
    networks:
      - mysql_network

volumes:
  asset_ms_dev:

networks:
  mysql_network:
    external: true
