services:
  nginx:
    container_name: asset_ms_dev_nginx
    build: ./docker/nginx
    ports:
      - 8001:80
    volumes:
      - "asset_ms_dev:/var/www/html"
    networks:
      - asset_ms_dev_network

  app:
    container_name: asset_ms_dev_app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 5001:5001
    volumes:
      - "asset_ms_dev:/var/www/html"
    networks:
      - asset_ms_dev_network

volumes:
  asset_ms_dev:

networks:
  asset_ms_dev_network:
